pipeline {
    agent any

    environment {
        BACKEND_IMAGE = "albertxp/todo-server:5.0"
        FRONTEND_IMAGE = "albertxp/todo-client:latest"
        KUBECONFIG = "/var/lib/jenkins/.kube/config"
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/bertoale/kelli.git', branch: 'main'
            }
        }

        stage('Build Docker Images') {
            steps {
                dir('backend') {
                    sh "docker build --no-cache -t $BACKEND_IMAGE ."
                }
                dir('client') {
                    sh "docker build -t $FRONTEND_IMAGE ."
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh "docker push $BACKEND_IMAGE"
                    sh "docker push $FRONTEND_IMAGE"
                }
            }
        }

        stage('Deploy to K3s') {
            steps {
                withEnv(["KUBECONFIG=/var/lib/jenkins/.kube/config"]) {
                    sh 'bash server-deploy.sh'
                    sh 'bash client-deploy.sh'
                }
            }
        }
    }
}
